<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Parent\Controllers\" />
    <Folder Include="Areas\Parent\Data\" />
    <Folder Include="Areas\Parent\Models\" />
    <Folder Include="Areas\Parent\Views\" />
    <Folder Include="Areas\Student\Controllers\" />
    <Folder Include="Areas\Student\Data\" />
    <Folder Include="Areas\Student\Models\" />
    <Folder Include="Areas\Student\Views\" />
    <Folder Include="Areas\Teacher\Controllers\" />
    <Folder Include="Areas\Teacher\Data\" />
    <Folder Include="Areas\Teacher\Models\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartEducation.Application\SmartEducation.Application.csproj" />
    <ProjectReference Include="..\SmartEducation.Infrastructure\SmartEducation.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartEducation.Persistence\SmartEducation.Persistence.csproj" />
    <ProjectReference Include="..\SmartEducation.Shared\SmartEducation.Shared.csproj" />
  </ItemGroup>

</Project>
