<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartEducation.Domain\SmartEducation.Domain.csproj" />
    <ProjectReference Include="..\SmartEducation.Shared\SmartEducation.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappings\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

</Project>
